17:30:51.507 INFO Test execution started: map_pin_test
17:30:51.508 INFO Browser: chrome
17:30:51.509 INFO Using data: 
    url: https://www.tentrr.com/s/sites/
    expected_text: Pioneer

17:31:02.064 INFO Navigate to: 'https://www.tentrr.com/s/sites/'
17:31:02.089 INFO Click #search-page > div > aside > div > div.leaflet-pane.leaflet-map-pane > div.leaflet-pane.leaflet-marker-pane > div.leaflet-marker-icon.site-pin.pin-pioneer-farm.leaflet-zoom-animated.leaflet-interactive
17:31:02.531 INFO Waiting for 3 seconds
17:31:05.541 INFO Assert that False is true
17:31:05.553 INFO Take screenshot error
17:31:07.346 INFO error__d31ecf4f
17:31:07.352 ERROR An error ocurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/golem_framework-0.5.0-py3.6.egg/golem/test_runner/test_runner.py", line 122, in run_test
    test_module.test(execution.data)
  File "/Users/yidong/golem/tentrr/projects/Tentrr/tests/map_pin_test.py", line 12, in test
    assert_true(data.expected_text in get_current_url())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/golem_framework-0.5.0-py3.6.egg/golem/actions.py", line 138, in assert_true
    raise Exception('Expected {} to be true'.format(condition))
Exception: Expected False to be true
