17:47:16.777 INFO Test execution started: map_pin_test
17:47:16.778 INFO Browser: chrome
17:47:16.779 INFO Using data: 
    url: https://www.tentrr.com/s/sites/
    expected_text: 44.14279782818058

17:47:23.672 INFO Navigate to: 'https://www.tentrr.com/s/sites/'
17:47:23.699 INFO Click #search-page > div > aside > div > div.leaflet-pane.leaflet-map-pane > div.leaflet-pane.leaflet-marker-pane > div.leaflet-marker-icon.site-pin.pin-pioneer-farm.leaflet-zoom-animated.leaflet-interactive
17:47:24.203 INFO Waiting for 3 seconds
17:47:27.216 INFO Assert that False is true
17:47:27.219 INFO Take screenshot error
17:47:28.929 INFO error__c654e4d8
17:47:28.931 ERROR An error ocurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/golem_framework-0.5.0-py3.6.egg/golem/test_runner/test_runner.py", line 122, in run_test
    test_module.test(execution.data)
  File "/Users/yidong/golem/tentrr/projects/Tentrr/tests/map_pin_test.py", line 12, in test
    assert_true(data.expected_text in get_current_url())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/golem_framework-0.5.0-py3.6.egg/golem/actions.py", line 138, in assert_true
    raise Exception('Expected {} to be true'.format(condition))
Exception: Expected False to be true
